-- Run in phpMyAdmin on dottbfyw_staging. Default delimiter `;` is fine.
-- Ignore errors like "Multiple primary key defined" or "Duplicate key name".

-- 1) Add PRIMARY KEY + AUTO_INCREMENT
ALTER TABLE `left_over_stock` ADD PRIMARY KEY (`id`);
ALTER TABLE `left_over_stock` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `login_logs` ADD PRIMARY KEY (`id`);
ALTER TABLE `login_logs` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `mailchimp_events` ADD PRIMARY KEY (`id`);
ALTER TABLE `mailchimp_events` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `migrations` ADD PRIMARY KEY (`id`);
ALTER TABLE `migrations` MODIFY `id` int UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `monthly_invoices` ADD PRIMARY KEY (`id`);
ALTER TABLE `monthly_invoices` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `monthly_invoices_detail` ADD PRIMARY KEY (`id`);
ALTER TABLE `monthly_invoices_detail` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `municipality_data` ADD PRIMARY KEY (`id`);
ALTER TABLE `municipality_data` MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `municipality_departments` ADD PRIMARY KEY (`id`);
ALTER TABLE `municipality_departments` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `nominees` ADD PRIMARY KEY (`id`);
ALTER TABLE `nominees` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `notifications` ADD PRIMARY KEY (`id`);
ALTER TABLE `notifications` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `notifications_code` ADD PRIMARY KEY (`id`);
ALTER TABLE `notifications_code` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `notifications_list` ADD PRIMARY KEY (`id`);
ALTER TABLE `notifications_list` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `notification_read_status` ADD PRIMARY KEY (`id`);
ALTER TABLE `notification_read_status` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `notification_types` ADD PRIMARY KEY (`id`);
ALTER TABLE `notification_types` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `oauth_clients` ADD PRIMARY KEY (`id`);
ALTER TABLE `oauth_clients` MODIFY `id` int UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `oauth_personal_access_clients` ADD PRIMARY KEY (`id`);
ALTER TABLE `oauth_personal_access_clients` MODIFY `id` int UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `organization` ADD PRIMARY KEY (`id`);
ALTER TABLE `organization` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `organization_location` ADD PRIMARY KEY (`id`);
ALTER TABLE `organization_location` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `pagebuilder_blocks` ADD PRIMARY KEY (`id`);
ALTER TABLE `pagebuilder_blocks` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `pagebuilder__pages` ADD PRIMARY KEY (`id`);
ALTER TABLE `pagebuilder__pages` MODIFY `id` int UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `pagebuilder__page_translations` ADD PRIMARY KEY (`id`);
ALTER TABLE `pagebuilder__page_translations` MODIFY `id` int UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `pagebuilder__settings` ADD PRIMARY KEY (`id`);
ALTER TABLE `pagebuilder__settings` MODIFY `id` int UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `pagebuilder__uploads` ADD PRIMARY KEY (`id`);
ALTER TABLE `pagebuilder__uploads` MODIFY `id` int UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `pages_services_assignments` ADD PRIMARY KEY (`id`);
ALTER TABLE `pages_services_assignments` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `pallets` ADD PRIMARY KEY (`id`);
ALTER TABLE `pallets` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `payments` ADD PRIMARY KEY (`id`);
ALTER TABLE `payments` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `payment_settings` ADD PRIMARY KEY (`id`);
ALTER TABLE `payment_settings` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `personal_access_tokens` ADD PRIMARY KEY (`id`);
ALTER TABLE `personal_access_tokens` MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `poc_assignments` ADD PRIMARY KEY (`id`);
ALTER TABLE `poc_assignments` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `product_brands` ADD PRIMARY KEY (`id`);
ALTER TABLE `product_brands` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `product_brand_images` ADD PRIMARY KEY (`id`);
ALTER TABLE `product_brand_images` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `product_related_items` ADD PRIMARY KEY (`id`);
ALTER TABLE `product_related_items` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `prompts` ADD PRIMARY KEY (`id`);
ALTER TABLE `prompts` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `prompt_document_types` ADD PRIMARY KEY (`id`);
ALTER TABLE `prompt_document_types` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `prompt_messages` ADD PRIMARY KEY (`id`);
ALTER TABLE `prompt_messages` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `property_purchaser_contacts` ADD PRIMARY KEY (`id`);
ALTER TABLE `property_purchaser_contacts` MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `property_purchaser_details` ADD PRIMARY KEY (`id`);
ALTER TABLE `property_purchaser_details` MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `property_types` ADD PRIMARY KEY (`id`);
ALTER TABLE `property_types` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `recipe_products` ADD PRIMARY KEY (`id`);
ALTER TABLE `recipe_products` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `redirect_pages` ADD PRIMARY KEY (`id`);
ALTER TABLE `redirect_pages` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `relationship_types` ADD PRIMARY KEY (`id`);
ALTER TABLE `relationship_types` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `reminders_sent` ADD PRIMARY KEY (`id`);
ALTER TABLE `reminders_sent` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `residence_status` ADD PRIMARY KEY (`id`);
ALTER TABLE `residence_status` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `sendinblue_webhook` ADD PRIMARY KEY (`id`);
ALTER TABLE `sendinblue_webhook` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `states` ADD PRIMARY KEY (`id`);
ALTER TABLE `states` MODIFY `id` mediumint UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `static_mapped_table_document` ADD PRIMARY KEY (`id`);
ALTER TABLE `static_mapped_table_document` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `static_pages` ADD PRIMARY KEY (`id`);
ALTER TABLE `static_pages` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `subscribed_notifications` ADD PRIMARY KEY (`id`);
ALTER TABLE `subscribed_notifications` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `subscription_email` ADD PRIMARY KEY (`id`);
ALTER TABLE `subscription_email` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `supplier_brand_assignment` ADD PRIMARY KEY (`id`);
ALTER TABLE `supplier_brand_assignment` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `supplier_product_assignment` ADD PRIMARY KEY (`id`);
ALTER TABLE `supplier_product_assignment` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `task_comment_typing_status` ADD PRIMARY KEY (`id`);
ALTER TABLE `task_comment_typing_status` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `transaction` ADD PRIMARY KEY (`id`);
ALTER TABLE `transaction` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `transaction_detail` ADD PRIMARY KEY (`id`);
ALTER TABLE `transaction_detail` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `trust_ledger_details` ADD PRIMARY KEY (`id`);
ALTER TABLE `trust_ledger_details` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `trust_ledger_summary` ADD PRIMARY KEY (`id`);
ALTER TABLE `trust_ledger_summary` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_subscribed_notifications` ADD PRIMARY KEY (`id`);
ALTER TABLE `user_subscribed_notifications` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `workflow_process_folders` ADD PRIMARY KEY (`id`);
ALTER TABLE `workflow_process_folders` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `workflow_process_notifications` ADD PRIMARY KEY (`id`);
ALTER TABLE `workflow_process_notifications` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `workflow_process_notifications_content` ADD PRIMARY KEY (`id`);
ALTER TABLE `workflow_process_notifications_content` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `workflow_process_statues` ADD PRIMARY KEY (`id`);
ALTER TABLE `workflow_process_statues` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `workflow_process_sub_activites` ADD PRIMARY KEY (`id`);
ALTER TABLE `workflow_process_sub_activites` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `workflow_sub_activites` ADD PRIMARY KEY (`id`);
ALTER TABLE `workflow_sub_activites` MODIFY `id` int NOT NULL AUTO_INCREMENT;

-- 2) Add AUTO_INCREMENT where PRIMARY KEY already exists
ALTER TABLE `aboutus` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `about_us_staff` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `access_rights` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `accounts` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `account_settings` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `account_setting_assignment` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `acquisition_source` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `additional_section_tabs_data` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `all_notifications_list` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `assets` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `assets_types` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `blogs` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `brand_related_products` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `casefile_activity_reminder` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `casefile_detail_documents` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `casefile_executed_documents` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `casefile_invoices` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `casefile_transactions` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `casefile_transaction_details` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `case_file_details` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `case_file_detail_sub_tasks` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `cities` MODIFY `id` mediumint UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `client_address` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `client_documents` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `client_employment_info` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `client_intake_form` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `client_intake_form_documents` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `client_intake_form_ids_documents` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `client_property_info` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `client_property_info_sub_details` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `client_relationships` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `company_information` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `company_poc_list` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `completed_tasks` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `compliance` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `compliances` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `contact_econtact_details` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `contact_form_backup_local` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `controllers` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `correspondences` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `correspondences_bk_14nov2023` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `correspondence_concerns` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `correspondence_mediums` MODIFY `id` int UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `correspondence_stages` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `correspondence_update_logs` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `countries` MODIFY `id` mediumint UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `currencies` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `customer_assignment` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `customer_delivery_ports` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `customer_documents` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `customer_images` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `customer_types` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `delete_logs` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `delivery_ports` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `departments` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `designations` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `documents_list` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `document_type` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `document_types` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `document_verifications` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `exchange_rates` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `exhibition` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `failed_jobs` MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `faqs` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `file_documents` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `file_document_assignment` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `file_document_placeholders` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `file_sub_documents` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `follow_up_reminders_sent` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `forwarder` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `genders` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `generate_document_tabs` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `generate_document_tabs_assignment` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `google_reviews` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `historical_records` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `home` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `intake_aps_documents` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `intake_forms` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `intake_form_inputs` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `intake_form_logs` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `intake_form_meetings` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `intake_form_meeting_assignment` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `intake_form_types` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `intake_form_witness` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `intake_poanwills` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `intake_post_sale_address` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `integrations` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `invoice_pdf_setting` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `jobs` MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `knowledge_content` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `knowledge_main_cat` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `knowledge_sub_cat` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `leads_followup` MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `lead_client_assignments` MODIFY `id` int NOT NULL AUTO_INCREMENT;
